### ISSUE TITLE
Should the individual converters really be provided as public classes?

### ISSUE THREAD

**Issue by mexx** [ploeh/Numsense#6]
In the mean of minimization of the public surface of the library, should the individual converters really be provided as public classes?

I mean, the normal way to access it would be through the `Numeral` class, right?

**Comment by ploeh** [comment]
Writing `Numeral.English.ToNumeral(42)` isn't a particularly object-oriented way of doing things, but I added it anyway for convenience.

In F#, the functions (like `Numeral.toEnglish`) are also values, which means that you can pass them around and use them for composition.

You can't do that in OOP... well, in C#, you can pass delegates around as well, because C# has been a hybrid language for many years now, but it's not *object-oriented*.

So, in order to offer an OOD API, I explicitly added the converters. You'll notice that they're covered by tests, so they are part of the public API.

**Comment by mexx** [comment]
I have no problem with the interface, this is the OOP way for providing the abstraction.
And since the users should only bind to the abstraction, I would only publish it to the users.

An instance of the implementation of this interface can be accessed by `Numeral.English`, as it wouldn't change anyway. Neither there is a need for inheriting from the implementation classes.

I'll provide a PR with the change I have in mind, so we can discuss with some code at hands ;)

**Comment by ploeh** [comment]
I think I see where you're going with this. If I understand you correctly, you want to make the converter constructors internal, so that the only way to access 'create' instances of e.g. `EnglishNumeralConverter` would be to access `Numeral.English`. Did I guess correctly?

**Comment by mexx** [comment]
Right, I've send a PR already.

**Comment by mexx** [comment]
Close it for the reasons elaborated in #7.
